[project]
name = "claude-usage-analyzer"
version = "0.1.0"
requires-python = ">=3.8"

dependencies = [
    "click>=8.1.0",
    "rich>=13.0.0",
    "python-dateutil>=2.8.0",
]

[tool.uv]
dev-dependencies = []